Remove botw_havok dependency
NiceneNerd/BCML pull request #487
Opened 2023-01-21 23:27 UTC by Nitr4m12

Since botw_havok is no longer used, this removes it as a dependency, while also updating numpy to its latest version which can be used on newer python versions

2023-01-22 01:50 UTC, GingerAvalanche commented
numpy 1.24.1 doesn't have a valid build for all the versions of python that BCML supports.

2023-01-22 11:32 UTC, Nitr4m12 commented
Just a thought, but why not remove numpy as well? It doesn't seem to be used directly in bcml

2023-01-22 23:02 UTC, GingerAvalanche commented
I took that suggestion and ran with it.

You are correct: without botw_havok, bcml no longer needs numpy.

As well, if pywebview is updated to 4.0.0+ and pythonnet to 3.0.1+ then py37 continues to work fine. I suspect that all python versions *above* py37 should also work fine (which would finally resolve the endless python versioning and dependency war we have going on).

If you can make those changes and test them for py38, that'll at least prove support for all python versions we explicitly support. If you want to also test py39 and py310, go ahead, but I'm willing to assume it'll work and hide behind "we're supporting what our readme says and also bcml is past EOL."

2023-01-22 23:07 UTC, GingerAvalanche requested changes
These are the changes I made in my last comment. Just mentioning them explicitly here so they're easier to copy in.

2023-01-22 23:07 UTC, GingerAvalanche commented on pyproject.toml
> +    "numpy~=1.24.1",
Remove

2023-01-22 23:07 UTC, GingerAvalanche commented on pyproject.toml
>      "pythonnet==2.5.2; platform_system == 'Windows' and python_version < '3.9'",
This and the next line can be replaced with `pythonnet~=3.0.1`

2023-01-22 23:07 UTC, GingerAvalanche commented on pyproject.toml
>      "pythonnet==2.5.2; platform_system == 'Windows' and python_version < '3.9'",
And because I can't comment on line 26 because it's too far, the pywebview dependency can be changed to `pywebview~=4.0.0`

2023-01-23 00:54 UTC, Nitr4m12 commented
Changes made, and confirmed building with python 3.7, 3.8, and 3.10

2023-01-23 01:23 UTC, GingerAvalanche commented
Does that mean no attempt for 3.9, or failed for 3.9?

2023-01-23 01:41 UTC, Nitr4m12 commented
3.9 did fail, but it my installation was corrupted or something. I reinstalled, tried again, and it worked.

2023-01-23 01:43 UTC, GingerAvalanche approved these changes

2023-01-23 01:44 UTC, merged